model_list:
  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: "os.environ/GOOGLE_API_KEY"

  - model_name: gemini-3-pro-preview
    litellm_params:
      model: gemini/gemini-3-pro-preview
      api_key: "os.environ/GOOGLE_API_KEY"

  - model_name: gpt-4.1
    litellm_params:
      model: openai/gpt-4.1
      api_key: "os.environ/OpenAI_API_KEY"

  - model_name: gpt-5.1
    litellm_params:
      model: openai/gpt-5.1
      api_key: "os.environ/OpenAI_API_KEY"

  - model_name: deepseek-reasoner
    litellm_params:
      model: deepseek/deepseek-reasoner
      api_key: "os.environ/Deepseek_API_KEY"
      drop_params: [ "tools" ]

  - model_name: openrouter-claude-sonnet-4.5
    litellm_params:
      model: openrouter/anthropic/claude-sonnet-4.5
      api_key: "os.environ/OpenRouter_API_KEY"
      api_base: "https://openrouter.ai/api/v1"

litellm_settings:
  telemetry: False
